[tool.ruff]
line-length = 100
select = [
	"F",
	"E", "W",
	"C90",
	"I",
	"N",
	"D",
	"UP",
	"YTT",
	"ANN",
	"S",
	"BLE",
	"FBT",
	"B",
	"A",
	"COM",
	"C4",
	"DTZ",
	"T10",
	#"DJ",  # django
	"EM",
	"EXE",
	"ISC",
	"ICN",
	"G",
	"INP",
	"PIE",
	"T20",
	"PYI",
	#"PT",  # pytest
	"Q",
	"RSE",
	"RET",
	"SLF",
	"SIM",
	"TID",
	"TCH",
	"INT",
	"ARG",
	"PTH",
	"ERA",
	#"PD",  # pandas
	"PGH",
	"PL",
	"TRY",
	#"NPY",  # numpy
	"RUF",
]
ignore = [
	# enable back later:
	"C901",  # "too complex"
	"ERA001", # commented out code
	# already managed by pulint, mb replace completely to ruff later:
	"PLR0912",  # too many branches
	"PLR0913",  # too many arguments
	"PLR0915",  # too many statements

	"PLE1205",  # pikaur is using non-default `logging`

	"ANN101",  # annotate self
	"ANN102",  # annotate cls
	"ANN401",  # disable Any

	"BLE001",  # disallow catching Exception

	"UP036", # remove code with py version checks

	# docstrings
	"D100",
	"D101",
	"D102",
	"D103",
	#
	"D105",
	"D107",
	"D203", # conflicts with D211
	"D205",
	"D212", # conflicts with D213
	"D400",
	"D401", # idk, it seems broken? pydocstyle.org is down so i can't check how it's supposed to work
	"D415",

	#"Q000",  # force double-quotes
]

[tool.ruff.per-file-ignores]
"pikaur/argparse.py" = [
	"PLR0912",
	"PLR0915",
	"SLF001",
]

"pikaur_test/*.py" = [
	"SLF001",
]
"pikaur_test/test_*.py" = [
	"ANN201",
	"ANN206",
	"PLR2004",
	"T201",
]
"maintenance_scripts/*.py" = [
	"INP001",
	"S301",
	"T201",
]
"maintenance_scripts/pikaman.py" = [
	"ARG002",
]
"maintenance_scripts/vulture_whitelist.py" = [
	"B018",
	"SLF001",
]
